##parameters=
"""CPS Geo Content Types
"""

cps_map_document_type = {
    'title': 'portal_type_CPSMapDocument_title',
    'description': 'portal_type_CPSMapDocument_description',
    'content_icon': 'document_map.png',
    'content_meta_type': 'CPS Map Document',
    'product': 'CPSGeo',
    'factory': 'addCPSMapDocument',
    'immediate_view': 'cpsmap_document_view',
    'global_allow': True,
    'filter_content_types': True,
    'allowed_content_types': (),
    'allow_discussion': False,
    'cps_is_portalbox': False,
    'cps_is_searchable': True,
    'cps_proxy_type': 'document',
    'cps_display_as_document_in_listing': True,
    'schemas': ('metadata', 'common', 'map_document'),
    'layouts': ('common', 'map_document'),
    'layout_clusters': ('metadata:metadata',),
    'flexible_layouts': (),
    'storage_methods': (),
    'cps_is_portlet': False,
    'cps_workspace_wf': ('workspace_content_wf',),
    'cps_section_wf': ('section_content_wf', ),
    'actions': (
         {'id': 'view',
          'name': 'action_view',
          'action': 'string:${object_url}/cpsmap_document_view',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': True,},
         {'id': 'new_content',
          'name': 'action_new_content',
          'action': 'string:${object_url}/folder_factories',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': True,},
         {'id': 'contents',
          'name': 'action_folder_contents',
          'action': 'string:${object_url}/folder_contents',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': True,},
         {'id': 'edit',
          'name': 'action_edit',
          'action': 'string:${object_url}/cpsdocument_edit_form',
          'condition': '',
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': True,},
         {'id': 'metadata',
          'name': 'action_metadata',
          'action': 'string:${object_url}/cpsdocument_metadata',
          'condition': 'not:portal/portal_membership/isAnonymousUser',
          'permission': ('View',),
          'category': 'object',
          'visible': True,},
         {'id': 'localroles',
          'name': 'action_local_roles',
          'action': 'string:${object_url}/folder_localrole_form',
          'condition': "python:object.getTypeInfo().cps_proxy_type != 'document'",
          'permission': ('Change permissions',),
          'category': 'object',
          'visible': True,},
         {'id': 'print',
          'name': 'action_print',
          'action': 'string:javascript:print_map_document();',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': True,},

    )
}

######################################################

types = {}
types['CPS Map Document'] = cps_map_document_type
return types
